### ISSUE TITLE
Epic #20 - Review of applications

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#100]
## Description
The Reviewer user should be able to make a review for Application's sections he/she is assigned to. There are a couple of ways to get to the Review page:
- From the action on the List of applications
- From the Application overview page
- From one notification link on the Dashboard
On the reviewing page the Review can only see/edit sections they are assigned to. Seeing other Reviewer comments is restricted by permissions.
The Reviewer can make a review and not submit. The review should be set to In-progress and the comments is only visible to them (no one else).
Refreshing the page also keeps all the Reviewer changes. When the user clicks Submit the Review is finished.

### Sprint 8:
- [x] #20 List concrete example of applications and actions for Reviewer (to send to Debs) - Effort 2

### Sprint 12:
- [x] [Back-end#131](https://github.com/openmsupply/application-manager-server/issues/131) Edit the review schema to consider changes on review process -  Effort 3
- [x] [Back-end#146](https://github.com/openmsupply/application-manager-server/issues/146) Add action to change status of review - Effort 2 
- [x] ~~[Back-end#132](https://github.com/openmsupply/application-manager-server/issues/132) Create reviewer user with basic permission associated to review company registration applications~~
- [x] [Back-end#136](https://github.com/openmsupply/application-manager-server/issues/136) Assign the Mock application template to the reviewer with all sections - Effort 1
- [x] [Back-end#135](https://github.com/openmsupply/application-manager-server/issues/135) Create new type of template "Mock template" and submitted application with assigned Reviewer - Effort 1
- [x] #159 Create review when Reviewer goes to the application review page - Effort 3

### Sprint 13:
- [x] #156 Show application page for Reviewer - Effort 2
- [x] #202 Trigger updates - Effort 3
- [x] #177 Show assigned to you on the section  - Effort 1 
- [x] #178 Approve all button & logic  - Effort 3

### Sprint 15:
- [x] #217 Collapsibility for application/review sections - Effort 4
- [x] #179 Decision on response in the suggestion panel after clicking the review button  - Effort 4 - ~**In PR**

### Sprint 16:
- [x] [Back-end#172](https://github.com/openmsupply/application-manager-server/issues/172) Break-down insertData - Effort 2

### Sprint 17:
- [x] #157 Submit application review - Effort 3

### Sprint 18:
- [x] #204 Add action to set the first review_status_history to DRAFT after the review is created - Effort 2
- [x] #176 Show error 404 page on application and review pages - Effort 2
- [x] #282 Diagram for Review status changes - Effort 2

### Sprint 19:
- [x] [Back-end#183](https://github.com/openmsupply/application-manager-server/issues/183) Add new Reviews for TestRego application with different status - Effort 2
- [x] #203 Update Review start page based on status - Effort 1

### Sprint 20:
- [x] #323 Refactoring to use same sections structure for progress in sections in Application, Progress bar and Review page - Effort 3
- [x] #175 Show progress of review on the section  - Effort 3 ~ **In PR - need changes to adapt to re-structure**

### Sprint 23:
- [x] #405 Click on Submit to take the user to firstNotDoneReview - using ref to move to correct place in the ReviewPage - Effort: AVG 2 ~ **In PR**

### Documentation
- [x] #200 Documentation for Review URL structure and routing - Effort 2
- [x] [Back-end#88](https://github.com/openmsupply/application-manager-server/issues/88) Review Process

**Comment by nmadruga** [comment]
Should consider new issues to deal with status `locked` when a Consolidation associated has been submitted using actions. The UI should display as the review is locked and then the Reviewer can't submit. Another action to unlock the reviews once the Consolidation has changed status
