### ISSUE TITLE
Misc Snapshot/Template Builder bugs 3

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1153]
Another one for fixing Template builder 🥲 

### Bugs found during configuration (April/2022)
- [x] #1152 
- [x] Lookup table loads forever loop if one column name is missing on import
- [x] Lookup table error if selecting a plural name for the table name
- [x] Wrong order of parameters on Page2 listing Information pre-filled
  - Bug: Wrong responses being saved with defaultValue https://github.com/openmsupply/application-manager-server/issues/733
![photo_2022-04-27 08 52 30](https://user-images.githubusercontent.com/16461988/165469109-5c73ef9d-8e7e-41b3-9987-c683d40bfef2.jpeg)
- [ ] Bug: Text field coming as isRequired as false otherwise is requiring something not-clear and won’t allow continuing
<img width="739" alt="Sub-module 1 info" src="https://user-images.githubusercontent.com/16461988/165468961-66395c4d-900f-4938-8010-0612b010e293.png">
- [ ] Bug: When editing field code or adding ANY new file upload something needs to reload the field to show on the Template without requiring a page-refresh
<img width="849" alt="Screen Shot 2022-04-27 at 10 50 03 AM" src="https://user-images.githubusercontent.com/16461988/165492079-e45800bf-d2b6-4632-b203-791694110aa9.png">

### Improvements
- [ ] Selecting "Static Text" or "Image Display" should set the category automatically to Information instead of Question. So we don't need to remember of doing this. Consequence of leaving this as Question - on the Summary list the applicant sees the ➕  icon indicating they can add a response, which isn't true. 
- [ ] #864
  - We probably need a simpler way to send notifications to the reviewer...
- [ ] #1043
- [ ] #1072
  - Front-end plugin config.json files should have the requiredParameters and optionalParameters objects (with label and type - idea of enum with selections i.e. Table, view, card
- [ ] When selecting an element type show link to the relevant documentation page - Add to manifest page
Connect the config.json files for each plugin to be passed in the manifest
- [ ] #934
  - Maybe that should be for any array element...
  - At least the ability to add on the top instead of the bottom of the array
- [ ] #1465
- [ ] Allow to remove template version from project

**Comment by CarlosNZ** [comment]
Pretty sure this is all taken care of by now.
