### ISSUE TITLE
Finalized translations - Portuguese

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1194]
### Reference
Final Requirements Matrix 1 - General - Row 5

* 2 days to finalise translations + PR review

### Configuration
- [x] Send email to PSM with strings in App for review - 30/05/202 
- [x] Check/Update translations on UserRegistration
- [x] Check/Update translations on U2-OrgRegistration
- [x] Check/Update translations on U3-OrgJoin
- [x] Check/Update translations on UserEdit
- [x] Check/Update translations on PasswordReset
- [x] Check/Update translations on GrantPermissions
- [x] Check/Update translations on CreateInternalUser
- [x] check all strings bellow are fixed in latest snapshot
- [ ] Update strings after reviewed by PSM into App -> This will be pending for a while... [Nicole] going to close the issue and we can create a separated one for when we need to update some string.

### Translations
Review home page
<img width="884" alt="Registro de Medicamento" src="https://user-images.githubusercontent.com/16461988/168003512-c69dd81c-9a07-47e2-ac3a-b691ad0c27a3.png">

Consolidation Section progress
<img width="151" alt="(32) Aprovado (0) Não" src="https://user-images.githubusercontent.com/16461988/168003532-acc8a98e-7cf2-4487-a5e9-2780c0ccba14.png">

Review history: 
	1) Decisions to Portuguese
	2) Solitiontante -> Requerente
<img width="870" alt="Material Manufacture," src="https://user-images.githubusercontent.com/16461988/168003577-b3143c11-1acc-46dd-b8df-5420ab175b4d.png">
<img width="886" alt="DISAGREE" src="https://user-images.githubusercontent.com/16461988/168003558-eae6dfa3-af74-4e84-9ea0-26e13ea017f7.png">

Filtros:
	1) Actions (avaliação & atribuição) to Portuguese
	2) Solicitante -> Requerente
	3) Fase -> Etapa
<img width="188" alt="Ações de avaliação" src="https://user-images.githubusercontent.com/16461988/168003608-60714939-15dd-48ac-bf94-894e72de7a7f.png">
<img width="164" alt="Ações de atribuição" src="https://user-images.githubusercontent.com/16461988/168003612-fa973440-c126-45f8-af62-99b64458edf2.png">
<img width="240" alt="Solicitante" src="https://user-images.githubusercontent.com/16461988/168003673-bd700488-9d3e-4815-a92c-2d0feb651c7a.png">

- Checkboxes plugin button to Portuguese
<img width="177" alt="Reset selections" src="https://user-images.githubusercontent.com/16461988/168003649-5e1032ac-f69b-4433-ab08-0de25aad6ab5.png">

- Fix Number plugin to Portuguese
<img width="197" alt="Quantidade" src="https://user-images.githubusercontent.com/16461988/168003689-24e90991-b940-44c0-a907-226dce29c9fa.png">

- Fix checkbox (toggle) plugin in Portuguese
<img width="455" alt="Medicamento sujeitos a receita médica" src="https://user-images.githubusercontent.com/16461988/168003707-f1d68d2a-cdfe-47d8-87bd-e22ac18f205a.png">
