### ISSUE TITLE
Preview documents

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#1203]
EPIC - see list of issue below

### Reference
Final Requirements Matrix 1 - Customisations - Row 2

* 8 days of development + tests
* 2 days review/documentation

- [x] Fix https://github.com/openmsupply/conforma-web-app/issues/1160 (extra?)
---

### Agreed solution:
https://github.com/openmsupply/conforma-web-app/issues/1203#issuecomment-1169449868

### Issue breakdown:

- [x] Action aliasing functionality: https://github.com/openmsupply/conforma-server/issues/768  
PR: https://github.com/openmsupply/conforma-server/pull/773
- [x] Create /preview-action endpoint: https://github.com/openmsupply/conforma-server/issues/769  
PR: https://github.com/openmsupply/conforma-server/pull/775
- [x] Create front-end UI and endpoint query: #1209  
PR: https://github.com/openmsupply/conforma-web-app/pull/1224
- [x] Clean up preview docs: https://github.com/openmsupply/conforma-server/issues/770  
PR: https://github.com/openmsupply/conforma-server/pull/777
- [x] Carbone template for LOQ Summary to applicant: https://github.com/openmsupply/conforma-server/issues/772  
Working example: https://github.com/openmsupply/conforma-server/issues/772#issuecomment-1173197654
- [x] Name and Description values for documents: https://github.com/openmsupply/conforma-server/issues/776  
PR: https://github.com/openmsupply/conforma-server/pull/775

**Comment by nmadruga** [comment]
Issue 1
- Schema change
- Template Builder UI
- Need to configure a message that is based on the decision: Approve or Reject. 
- Permissions tab have a way to add specific messages depending on the decision. We should have default messages to be shown in case: is last level for conform, Changes requested (to reviewer) list of question (to applicant) or non-conform and also when is not last level to explain it is going to the next level review.

Issue 2
- Send to the action the list of question (and the answers as text) to be included in the generated Carbone template
- Setup Carbone template for LOQ example
- Preview might be not possible, we should use a link to the pdf
- How to generate the PDF once the reviewer clicks to preview? 
  - It can be using the End-point or it can be using the action based on a new EVENT... 

Issue 3
- Have defaults for each decision/level to improve time on configuration
- https://github.com/openmsupply/application-manager-web-app/issues/1207

**Comment by CarlosNZ** [comment]
Okay, @andreievg and I had a planning discussion this morning about how this might actually work, and here's a summary of what we had in mind. There may be complications we've overlooked, so I'll try to be as detailed as possible here:

### 1. New endpoint for "previewing" actions `/preview-action`

The difference between this endpoint and the existing "run-action" endpoint (apart from the fact that run-action is intended for dev only and should never be part of the system) is that this one is for calling specific "template_action" instances that are defined in the template_action table and associated with a template. Therefore the "preview" action can be defined in the existing template builder Action page and have parameters and conditions defined in the template accordingly. So the endpoint can't just fire off any old action with any parameters, only call specific action instances that are already defined in the current template.

One problem we considered is that a "preview" action might sometimes require data that has not been generated yet (e.g. a review decision value, or a status) and that won't be generated until AFTER the review has been submitted for real. So, this "preview-action" endpoint can also supply "applicationData" fields. So what happens is the preview action runs like a normal action and generates its "applicationData" object, but then the supplied fields over-ride that, so we can simulate a particular review_decision for example.

The front end would just call this "preview_action" endpoint, wait for the response, then preview the returned data accordingly (more on that below)

The endpoint should also probably contain some metadata about how to structure/display the output in the front-end. Presumably this would be based on plugin-type: files get opened in new tab and downloaded, others get displayed as text, say

### 2. How does the trigger and action system handle these "previews"?

- Create a new trigger value called "ON_PREVIEW"
- The "preview" endpoint never actually sets this trigger, but it calls the "processTrigger" function directly, and just passes this trigger value in (would need to construct it into a dummy "TriggerPayload" object)
- Then the "preview" actions just run as defined in the template and returns the final output to the endpoint

So the things we'd need to change in the existing back-end code (other than the endpoint itself) are:
1. Some way for the trigger/action mechanism to inject the "override" fields when it creates the "applicationData" object
2. Some way to return the final output data from the action sequence (currently it just gets written to the database action queue record)

Suggested solutions to these two problems to cause minimal disruption to existing functionality:
- add an additional field "preview_parameters" to the "action_queue" table, into which the endpoint's parameters are inserted (passed along through the dummy "TriggerPayload" object. Then it would get carried along to the "executeAction" function in the "ActionPayload" object, and we'd just need to make a small tweak to the "getApplicationData" function to insert these values at the end.
- Just add a "return" statement to the end of "processTrigger" to pass the output values back to the endpoint method. (We could read the values from the database, but the endpoint method would still need to know when the "processTrigger" was "done", so it's just as simple to return it directly.)

### 3. Template configuration

There's no need for any additional template configuration -- just adding more actions to the Actions page with the new "ON_PREVIEW" trigger (with appropriate conditions for review level, etc.)

It is apparent though, that these "Preview" actions will be almost identical copies to the "actual" actions that run on submission. It would be a hassle to define and maintain these twice, especially since some of the "generateDoc" actions are quite complicated with a lot of parameters. So we thought it would be good to create a new action "aliasAction", which just allows you to define a reference to an existing template_action rather than configure it completely from scratch. The only compulsory parameter would be "actionCode" which would link to the "code" field of the action being aliased. We're currently not using the "code" field in "template_action", so now would be a good time to start. We'll need to add a UI  to template builder to insert "code" for actions though as we currently only have "scheduledEventCode"

You can also supply additional parameters to the "aliasAction" action though, if you need to override them. For example, for an "email" action, we'd want the simulated version to not actually send an email, so you'd need to set the (existing) "sendEmail" field to "false" in the aliased version,  but all other parameters would be the same.

I'll put a bit more detail on exactly how this action would work into the actual issue when I get to it, but in principle this seems sound. At runtime, it'll basically just lookup the referenced template_action, then run it as though this were it, but with override parameters inserted.

### 4. Front-end UI

**Template builder**:
- add "code" field input for actions
- add "ON_PREVIEW" to list of available triggers (if not auto-generated from enum -- I can't remember)

**Review page**:
- At the bottom of the page, alongside the "Decision" area, we add an additional button called "Preview"
- When preview is clicked, it launches a Modal which informs the user that a preview of documents/messages sent to user is being generated (with a Loading spinner)
- Modal component calls the `preview-action` endpoint, with applicationId, reviewId as the main trigger parameters, and "reviewDecision" value (based on current selection in UI -- Approved, Request Changes, Rejected) as the "override" parameters which are sent to "applicationData" (_any other parameters we should send? -- and is this just a fixed set of values, or does it need to be configurable?_)
- Once the endpoint returns the action output, we parse it accordingly (based on metadata) and display a link in the modal to each one. Clicking a link opens (always in a new tab?) the action data (either PDF or HTML display) for previewing. (_This needs a little more thought as to how to elegantly display email text -- accordion within Modal perhaps?_)

This way, the reviewer can change their decision and preview the different outputs based on different cases before submitting.

### 5. Clean-up

Obviously this process will generate a large amount of "garbage" in terms of preview docs that are never seen again. Suggestion is to just add an additional field "is_preview" to the file table and mark it "TRUE" for all these preview docs. (ideally we'd have some way to make this happen automatically -- perhaps the endpoint always injects the parameter?)
Then we just add a function that runs on a schedule (once per day) and deletes any documents that are marked "is_preview" (and are more than, say, 1 hour old -- we don't want to delete docs that are haven't been downloaded yet, in case the reviewer is doing previews when the cleanup function runs)

#### Remaining questions

The one things that's not totally clear to me is whether we need any additional configuration that can't be defined in the existing template_action config (conditions and parameters). I'm thinking not, but please highlight any use cases which might require it in case we've overlooked something. If it's just a matter of changing "state" values (e.g. status/outcome) depending on Decision, we should be able to define it in the "aliasAction" parameters (i.e we define expressions for additional "simulated applicationData" along with any action parameter overrides) (though the decision itself will be passed directly to the endpoint)

Please add any comments or potential problems here, and I'll break this down into issues in a couple of days.

**Comment by andreievg** [comment]
Thank! I think this would work, hopefully no major setbacks/edge cases arise during implementation.

> The endpoint should also probably contain some metadata about how to structure/display the output in the front-end. Presumably this would be based on plugin-type: files get opened in new tab and downloaded, others get displayed as text

Hope it's a nice to have that we can skip

>  and we'd just need to make a small tweak to the "getApplicationData" function to insert these values at the end.

I would need to look at the code to confirm this, but would imagine the preview end point can do these steps separately ? I.e. getApplicationData then override it ? (just to keep the method conditions from bloating) 

> Please add any comments or potential problems here, and I'll break this down into issues in a couple of days.

Would be nice to summarise present conditions for the document generation actions in current config (when issue is broken down).

**Comment by CarlosNZ** [comment]
> > The endpoint should also probably contain some metadata about how to structure/display the output in the front-end. Presumably this would be based on plugin-type: files get opened in new tab and downloaded, others get displayed as text
> 
> Hope it's a nice to have that we can skip

Yeah, there's really only two types of content returned that I can think of:
- urls to PDF files
- email/notification text (Markdown)

I suggest the endpoint bundles them into an array of objects such as:
```
{
  type: file / text
  content: Url / MarkdownText
}
```
Then displays it accordingly. :)

> > and we'd just need to make a small tweak to the "getApplicationData" function to insert these values at the end.
> 
> I would need to look at the code to confirm this, but would imagine the preview end point can do these steps separately ? I.e. getApplicationData then override it ? (just to keep the method conditions from bloating)

Yup, for sure. It can slot nicely into `executeAction` (passed in through ActionPayload) and we can leave `getApplicationData` untouched.

> Would be nice to summarise present conditions for the document generation actions in current config (when issue is broken down).

You mean which templates get which preview at which stage, etc.? Yeah, I figured I'd build that into one of our existing templates while developing so we can test it working.

**Comment by jagoje** [comment]
> * (_any other parameters we should send? -- and is this just a fixed set of values, or does it need to be configurable?_)

No just the three. But I note that in the UI the names are not always consistent, I assume this doesn't affect anything though.

**Comment by CarlosNZ** [comment]
> 

That's all good -- the names in the code are consistent ;)

Thanks for the clarification.

**Comment by jagoje** [comment]
Ok I have read through, some of course goes over my head.. 

But all sounds good. I think that all cases will be tied back to that outcome/decision field, if that answers that, I can write out a specific list of user stories if helpful?

I have attached an image of what Nicole imagined (not sure if she is reading!), which was repurposing the confirm submission page, just for reference in case this is easier. However - I like the preview button being a there near the decision fields.

**Comment by nmadruga** [comment]
Closing issue since feature seems to be all in there.
