### ISSUE TITLE
Add "Loading" spinners/waiting for more items

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#1261]
Noticed during the recent presentation that there's not UI feedback when certain items are loading. We don't notice it in dev because they appear super-fast, but on a slow connection, it's quite disconcerting, so could use some user feedback.

In particular:
- [x] Loading spinners PR #1262 
- [x] Application list - PR #1262 
- [x] Assignments (on Assignments tab) -- #1375
- [ ] Templates page
- probably some others...

**Comment by CarlosNZ** [comment]
Maybe you could try, @fergie-nz ?

If you do, check in with me before you start and I'll point you in the right direction.

**Comment by CarlosNZ** [comment]
Seems like we've done most of these...
