### ISSUE TITLE
Epic #22 - Consolidation of Reviews

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#165]
## Description

The Consolidator - that can be also called a higher level Reviewer - is the user in charge to respond to the Applicant after some reviews have been submitted. The consolidation process is divided in two steps:
1. Check the decisions done by the lower level Reviewers and **conform** or **non-conform** with the reviews
2. (one a new page?) Confirm consolidator decision based on differences of Review decision and Consolidation decision:
    - Reviewer `approved` all + Consolidator `conform` with all => Application is changes to next stage & Applicant gets feedback.
    - Reviewer `approved` all + Consolidator `non-conform` with at least one => Reviewer get's **Changed required**
    - Reviewer `declined` at least one + Consolidator `conform` with all => Application is **Rejected** OR changes status to **Changes requested** & Applicant gets feedback (LOQ.
    - Reviewer `declined` at least one + Consolidator `non-conform` with all => Reviewer get's **Changed required**

A Consolidator should be able to see submitted applications with all reviewers assigned to sections and review statuses. When opening the consolidation page they should view the current submitted reviews (or lower level consolidation) and be able to start the consolidation - when they have permission to - after the first reviewer has submitted. Or before any review is done they can only view the application without any option to start consolidation. 
 
After the first review is submitted (each review can be associated to one or more sections) one consolidation can be started. The Consolidator sees applications with consolidation PENDING/OPEN status. Only one consolidator should be able to work on a consolidation of the same application (in the same stage). After starting the consolidation it changes to status DRAFT and other possible Consolidator will see LOCKED statuses. During the consolidation - with status DRAFT - if another review for this same application is submitted, a warning should be displayed to the Consolidator, and change the consolidation to PENDING status. The Consolidator user needs to click **continue** to see the new reviews.
  
On the consolidation page the user can select to **conform**/**non-conform** to existing review decisions and comments. Very similar to a review, they go one by one selecting their decision and adding comments - if non-conform.
There is an extra step at the end, to decide (and confirm) the decision on this consolidation:
* Ask Reviewer for **Changes required**
* Ask Application for **Changes requested**
* Approve application
* Reject application

If there is another Reviewer level on top of the current Consolidator, then they don't get to see the 3 later options, only the highest level of Consolidator can make that decision - that will lead to a feedback to the Applicant. 

## Documentation
- [x] https://github.com/openmsupply/application-manager-web-app/issues/269
- [x] https://github.com/openmsupply/application-manager-server/issues/212
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials

### Sprint 17
- [x] #281

### Sprint 18:
- [x] #291
- [x] https://github.com/openmsupply/application-manager-server/issues/189
- [x] https://github.com/openmsupply/application-manager-server/issues/196

### Sprint 19:
- [x] https://github.com/openmsupply/application-manager-server/issues/188
- [x] #307
- [x] https://github.com/openmsupply/application-manager-server/issues/205
- [x] https://github.com/openmsupply/application-manager-server/issues/207
- [x] #274
- [x] https://github.com/openmsupply/application-manager-server/issues/195

### Sprint 20:
- [x] https://github.com/openmsupply/application-manager-server/issues/199

### Sprint 23:
- [x] #277

### Sprint 24:
- [x] #428

### Sprint 25:
**Moved from Epic#21 - Re-structure**
- [x] #389
- [x] #391
- [x] #388
- [x] #392
- ~~#355~~
- [x] #463

### Sprint 26:
- [x] #273
- [x] #387
- [x] #495 

### Sprint 29:
- [x] #390 PR #631 & https://github.com/openmsupply/application-manager-server/pull/318
- [x] #295 PR #632

### Sprint 31:
- [x] #275
- [x] #276
- [x] #634

### Sprint 32:
- [x] #357

**Comment by nmadruga** [comment]
Considering to create consolidation_responses as actions (for when partial reviews are included during the consolidation) which could also be a pattern to be changed and make all responses be created as actions after a creation action happens (e.g. Create application).

**Comment by nmadruga** [comment]
Think about two points discussed in meeting 26/01/2021:
* Thinking about getting review_assignments to all consolidator when Application is submitted, what happens for **new** consolidator that get permissions, now they don't have assignment to current applications.
* For withdrawn consolidation review - one of the other consolidators could continue the work by changing the review status to `open` and perhaps authorising the withdrawn consolidation to be relinked to the new consolidator.
