### ISSUE TITLE
Epic #14 - Application Submit

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#173]
On clicking "**Submit**" button:

- Re-validation (new calculation), so we can be sure everything is valid NOW (there may be some significant delay between filling in form and submitting it) (**make new issue**)
   - If Validation fails, show modal, then re-direct user to first invalid question.

If Validation is okay:

- Set ApplicationTrigger to `onApplicationSubmit` (**Done**)
- Wait until Application Trigger resets to `NULL` (with Timeout) ([Issue card](https://github.com/orgs/openmsupply/projects/6#card-49487563))
   - If timeout reached, inform user via modal of a problem, and inform system admin (via back-end Action?) **TO-DO**

If Submission Okay so far:
- Inform user of successful submission via modal (or new page), including template "Success" message (check email, whatever) **TO-DO**

After user clicks "OK" on modal:
- If user is `nonRegistered`, log out. #150 
- Else, redirect to Dashboard **TO-DO**

---

When loading Summary page:
- Currently, it performs re-validation and displays result in Summary. This is **under discussion**.

### Sprint 8
- [x]  #103 Redirection to the summary in case the application is submitted - Effort 2
- [x] #85 Needs to add newly application to cache in order to show on the list of applications - Effort 1
- [x] #45 Mutate application from cache - Effort 4
- [x] #114 Bug fixes for application loading/submitting - Effort 1
- [x] #113 Create application mutation in single-block- Effort 1

### Sprint 9
- [x] #68 Display application View page when click an application with Submitted status - Effort 1

### Sprint 11
- [x] #143 Unify types and reuse of evaluated responses object on SummaryView and ApplicationView - Effort 3
- [x] #122 Create link to sections from the Summary page - Effort 1
- [x] #158 Summary Wrapper -- validation - Effort 2

### Sprint 12:
- [x] #48 check validation of progress structure before submission - Effort 1
- [x] #193 Redirect to last page with invalid elements when user loads Summary of application invalid - Effort 1
