### ISSUE TITLE
Epic #23 - Dashboard

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#249]
### Description
When the user logs in that's the first page they see and where they can get to each Template they have access.
Now this Dashboard isn't configurable, it would always show the user most recent activity and notifications.
There are links to open specific applications of User's interest from the Dashboard. And links to the list of applications using certain filters.

### Documentation
- [ ] Documentation on how to configure dashboards #725
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials

### Sprint 31:
- [x] Add dashboard layout (from demo) using categories - not filter filters #639
- [x] Options to filter list by number using the fields from Application view list for reviewer and assigner #640
- [x] Display on the dashboard the number of application based on the filters #641

### Sprint 32:
- [x] Add categories and filters into template schema inserts [Back-end#322](https://github.com/openmsupply/application-manager-server/issues/322)
- [x] #698 PR dashboard functionality from demo
- [x] Ask Debbie to refine dashboard look

### Sprint 40:
- [x] #824 
- [x] #830
