### ISSUE TITLE
Epic #33 - Application to PDF templates

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#333]
### The Idea

Template/s can be configured for each submission (for application/review at each stage, level and decision).  A pdf is generated (to look as per DDF requirements). It is generated on submission and can be previewed before submission. (this is the document that can be sent to applicant, via email).

### Tasks 

- [ ] [#438](https://github.com/openmsupply/application-manager-web-app/issues/438) Spec out what data will be available for the template for application and review, and show an example of how templating with Carbone works
- [ ] [#439](https://github.com/openmsupply/application-manager-web-app/issues/439) Spec out proposed schema changes
- [ ] Apply proposed schema changes
- [ ] Add Carbone to back end with endpoint (for document preview), and make it accessible to actions (to generate and attach document to application/review (to b in above tasks speced above)
- [ ] Make preview accessible in front end and generated saved document accessible (where ? in the submission view ?)

**Comment by nmadruga** [comment]
We need to show something to the Reviewer that would be displayed as a document, with the LOQ or perhaps a summary with all **Approved** and **Rejected** to be sent back to Applicant or Reviewer.
