### ISSUE TITLE
Epic #34 - Application final decision

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#334]
## Description

This is also covered pretty similar to the whole review process, but require a change to the **outcome** of the application as well as generating certificates to the applicant (other epic).

## Documentation
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials

### Sprint 41:
- [x] https://github.com/openmsupply/application-manager-server/issues/445 PR https://github.com/openmsupply/application-manager-server/pull/452
- [x] https://github.com/openmsupply/application-manager-server/issues/446 PR https://github.com/openmsupply/application-manager-server/pull/453
- [x] #835 PR #843
- [x] #834 PR #843
- [x] https://github.com/openmsupply/application-manager-server/issues/447 PR https://github.com/openmsupply/application-manager-server/pull/460

### Sprint 42:
- [x] https://github.com/openmsupply/application-manager-server/issues/461 PR https://github.com/openmsupply/application-manager-server/pull/464
- [x] https://github.com/openmsupply/application-manager-server/issues/251 PR https://github.com/openmsupply/application-manager-server/pull/464
- [x] https://github.com/openmsupply/application-manager-server/issues/251

### Sprint 43:
- [ ] #737
- [ ] #836
- [x] https://github.com/openmsupply/application-manager-server/issues/448
- [ ] https://github.com/openmsupply/application-manager-server/issues/476
- [x] #870 
- [ ] #871

### Next sprint:
- [x] https://github.com/openmsupply/application-manager-server/issues/405

### Backlog
- ~~#278~~ DUPLICATE
- ~~#279~~ DUPLICATE
