### ISSUE TITLE
Epic #40 - Country Specific config

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#340]
### Sprint 35:
- [x] https://github.com/openmsupply/application-manager-server/issues/383
- [x] #762 PR #763 
- [x] https://github.com/openmsupply/application-manager-server/issues/377 - (break-down below)
- [x] https://github.com/openmsupply/application-manager-server/issues/376 (break-down below)
- [x] https://github.com/openmsupply/application-manager-server/issues/388
- [x] https://github.com/openmsupply/application-manager-server/issues/384

### Sprint 36:
- [x] https://github.com/openmsupply/application-manager-server/issues/406

### Sprint 37:
- [x] https://github.com/openmsupply/application-manager-server/issues/398

### Sprint 38:
- [x] https://github.com/openmsupply/application-manager-server/issues/385

### Sprint 47:
- [x] https://github.com/openmsupply/application-manager-server/issues/405
- [x] https://github.com/openmsupply/application-manager-server/issues/478

### Sprint 49:
- [x] https://github.com/openmsupply/application-manager-server/issues/333
- [ ] https://github.com/openmsupply/application-manager-server/issues/507

### Next sprint:
- [ ] https://github.com/openmsupply/application-manager-server/issues/389
- [ ] https://github.com/openmsupply/application-manager-server/issues/370
- [ ] https://github.com/openmsupply/application-manager-server/issues/419
- [ ] https://github.com/openmsupply/application-manager-server/issues/418
- [ ] https://github.com/openmsupply/application-manager-server/issues/457
- [ ] #756
- [x] https://github.com/openmsupply/application-manager-server/issues/536

**Comment by nmadruga** [comment]
MMC - MMM MDC MDM WSL and RIT

2 stages (1 level per stage)
- Pool of screeners - self-assigning (for whole screening)
- Assessment ?

Pre-filled using current use info:
- applicant name
- date if birth
- national ID (needs to be included in the user registration - later) Just add a textInfor for now!
- date of issue (for national ID)
- Current adrress
- Education (List builder)
  - university 

Q: Is the user the applicant?

----

List builder (with options):
- professional experience
  - government
  - private sector
- Name of institution (if government)
- Name of company (if private section)
- Period of role
- Telefone
- email

----

Purpose of application (radioChoice):
- One of the four option to generate a different type of registration (number for now)
- The import/export would grant permission to apply for "Drug Registrations"

----
No worries about other templates for this first iteration or adapting current "Drug registration"

Other stuff related to what needs to be in there for delivery:
- List of companies with important fields (dynamically added based on outcomes) 
- Think how to import many companies to current tables with dynamic fields
