### ISSUE TITLE
Epic #45 - Applicant view applications by permission (permissionPolicy config)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#504]
## Description
See only applications made by them (user_id) or made by the organisation (org_id). But should only be able to edit application in case it's their own (or higher privileges - i.e: org owner).

## Permission policies
Each type defines View, Edit and Apply permissions 

- Apply-by-session (Non-registered)
- Apply-by-user
- Apply-by-org

## Templates with Policies (view permissionName)

- User Registration - Apply-by-session
- Feature Showcase - Apply-by-user
- Drug registration - Apply-by-org
- Test Review - Apply-by-org
- Join Company - Apply-by-user
- Edit user-details -Apply-by-user

## Permission Policy restrictions:

- Apply-by-user
application
  * View ->  All with user_id = jwt user_id
  * Create -> NEW.user_id = jwt user_id, org_id = null
  * Update -> (inherits view) -> is DRAFT, NEW.user_id =  jwt user_id, etc (but we only want to allow change to trigger!)
application_response
 * View -> All with matching application
 * Create -> 
 * Update -> If DRAFT
review_response
  * View -> is_vissible to application = true, and linked to application _responses above
  * Create -> no
  * Update -> no

## Documentation
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials

### Sprint 32:
- ~~#603~~ INVALID
- [x] #342
- [x] #687
- [x] https://github.com/openmsupply/application-manager-server/issues/344

### Sprint 48:
- [ ] https://github.com/openmsupply/application-manager-server/issues/343
