### ISSUE TITLE
Epic #62 - View other's Review (permissionPolicy configurations)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#524]
## Description

Users with permisson to VIEW should be allowed to see other reviews pages done by others. And on the Review Home-page see all the information and make comments to show on internal comments area. 

## Documentation
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials

## Issues
- [x] #356 Show 404 on Review page when changing to user without permission or not assigned
- [ ] Add new option on Template builder to associate VIEW permission
- [ ] Allow users with VIEW permission on the Review home page and Review page

**Comment by andreievg** [comment]
From row **level policies perspective**:

- [ ] Add new policy type `VIEW`, [this branch](https://github.com/openmsupply/conforma-server/compare/Permission-policy-of-type-view)

* Configure policy with these rules (see below for graphql mutation):

```json
{
    "review": {
        "view": {
            "application_id": {
                "$select": {
                    "$from": "review_assignment",
                    "$where": {
                        "$and": [
                            {
                                "template_id": {
                                    "$eq": "jwtPermission_array_bigint_template_ids"
                                }
                            }
                        ]
                    },
                    "$columns": {
                        "application_id": true
                    }
                }
            }
        }
    },
    "application": {
        "view": {
            "id": {
                "$in": {
                    "$select": {
                        "$from": "review_assignment",
                        "$where": {
                            "$and": [
                                {
                                    "template_id": {
                                        "$eq": "jwtPermission_array_bigint_template_ids"
                                    }
                                }
                            ]
                        },
                        "$columns": {
                            "application_id": true
                        }
                    }
                }
            }
        }
    },
    "review_assignment": {
        "view": {
            "reviewer_id": {
                "$isNull": false
            },
            "template_id": "jwtPermission_array_bigint_template_ids"
        }
    }
}
```

Which translates to:

(fyi: `COALESCE(current_setting('jwt.claims.pp123', true), '') != ''` will check that permission policy is linked to user through permission joins -> permission name and `any(string_to_array(COALESCE(current_setting('jwt.claims.pp123_template_ids', true), '0'), ',')::integer[])` would give all template_ids for that policy linked to user through permission joins`)

`can view all reviews with review_assignments for template_id that is linked to this permission policy`

```sql
CREATE POLICY "view_pp123" ON "review" FOR 
SELECT 
  USING (
    COALESCE(
      current_setting('jwt.claims.pp123', true), 
      ''
    ) != '' 
    and application_id (
      SELECT 
        application_id 
      FROM 
        review_assignment 
      WHERE 
        template_id = any (
          string_to_array(
            COALESCE(
              current_setting(
                'jwt.claims.pp123_template_ids', 
                true
              ), 
              '0'
            ), 
            ','
          ):: integer[]
        )
    )
  )
```

`can view all applications with review_assignments for template_id that is linked to this permission policy`

```sql
CREATE POLICY "view_pp123" ON "application" FOR 
SELECT 
  USING (
    COALESCE(
      current_setting('jwt.claims.pp123', true), 
      ''
    ) != '' 
    and id IN (
      SELECT 
        application_id 
      FROM 
        review_assignment 
      WHERE 
        template_id = any (
          string_to_array(
            COALESCE(
              current_setting(
                'jwt.claims.pp123_template_ids', 
                true
              ), 
              '0'
            ), 
            ','
          ):: integer[]
        )
    )
  )

```

`can view all review_assignments with template_id that is linked to this permission policy`

```sql
CREATE POLICY "view_pp123" ON "review_assignment" FOR 
SELECT 
  USING (
    COALESCE(
      current_setting('jwt.claims.pp123', true), 
      ''
    ) != '' 
    and reviewer_id IS NOT NULL 
    AND template_id = any (
      string_to_array(
        COALESCE(
          current_setting(
            'jwt.claims.pp123_template_ids', 
            true
          ), 
          '0'
        ), 
        ','
      ):: integer[]
    )
  )
```

- [ ] Add VIEW option to template builder [this branch](https://github.com/openmsupply/conforma-web-app/compare/Permission-of-type-view-in-template-builder)

- [ ] Create policy

```graphql
mutation AddViewAllPolicyAndPermissionName($rules: JSON) {
  __typename
  createPermissionPolicy(
    input: {
      permissionPolicy: {
        name: "viewAllReviews"
        description: "View all reviews"
        rules: $rules
        permissionNamesUsingId: {
          create: { description: "View all reviews", name: "viewAllReviews" }
        }
        type: VIEW
      }
    }
  ) {
    clientMutationId
  }
}
```

`variables`

```json
{
    "rules": {
        "review": {
            "view": {
                "application_id": {
                    "$select": {
                        "$from": "review_assignment",
                        "$where": {
                            "$and": [
                                {
                                    "template_id": {
                                        "$eq": "jwtPermission_array_bigint_template_ids"
                                    }
                                }
                            ]
                        },
                        "$columns": {
                            "application_id": true
                        }
                    }
                }
            }
        },
        "application": {
            "view": {
                "id": {
                    "$in": {
                        "$select": {
                            "$from": "review_assignment",
                            "$where": {
                                "$and": [
                                    {
                                        "template_id": {
                                            "$eq": "jwtPermission_array_bigint_template_ids"
                                        }
                                    }
                                ]
                            },
                            "$columns": {
                                "application_id": true
                            }
                        }
                    }
                }
            }
        },
        "review_assignment": {
            "view": {
                "reviewer_id": {
                    "$isNull": false
                },
                "template_id": "jwtPermission_array_bigint_template_ids"
            }
        }
    }
}
```

- [ ] Add permission policy to templates (I don't think it will affect existing templates, would have to manually link with graphql)

This should be all from **row level policy**, sorry I am still busy with omSupply sync, can someone please test this @fergie-nz  ?

**Comment by nmadruga** [comment]
Hey, it took us some time to be able to test this, but after a few attempts today I can only say this code doesn't do what was expected. Is hard to know where is the problem. So I'm trying to get your help on this again...

Basically when applying this rules - there is no changes to the Reviewer. They can't see others reviews.

I noticed that these rules are following a slight different pattern from previous ones:

> ```json
> {
>     "rules": {
>         "review": {
>             "view": {
>                 "application_id": {
>                     "$select": {
>                         "$from": "review_assignment",
>                         "$where": {
>                             "$and": [
>                                 {
>                                     "template_id": {
>                                         "$eq": "jwtPermission_array_bigint_template_ids"
>                                     }
>                                 }
>                             ]
>                         },
>                         "$columns": {
>                             "application_id": true
>                         }
>                     }
>                 }
>             }
>         },
>         "application": {
>             "view": {
>                 "id": {
>                     "$in": {
>                         "$select": {
>                             "$from": "review_assignment",
>                             "$where": {
>                                 "$and": [
>                                     {
>                                         "template_id": {
>                                             "$eq": "jwtPermission_array_bigint_template_ids"
>                                         }
>                                     }
>                                 ]
>                             },
>                             "$columns": {
>                                 "application_id": true
>                             }
>                         }
>                     }
>                 }
>             }
>         },
>         "review_assignment": {
>             "view": {
>                 "reviewer_id": {
>                     "$isNull": false
>                 },
>                 "template_id": "jwtPermission_array_bigint_template_ids"
>             }
>         }
>     }
> ```

So I tried changing to what I would expect, from looking at the other policies... 
But this is breaking it even more, by not adding any visibility on reviews for any user, this is the version I attempted:
```
{
  "review":{
    "view":{
      "application_id":{
        "$in":{
          "$select":{
            "$from":"review_assignment",
            "$where":{
              "template_id":"jwtPermission_array_bigint_template_ids"
            }
          },
          "application_id":true
        }
      }
    }
  },
  "application":{
    "view":{
      "id":{
        "$in":{
          "$select":{
            "$from":"review_assignment",
            "$where":{
              "template_id":"jwtPermission_array_bigint_template_ids"
            }
          },
          "application_id":true
        }
      }
    }
  },
  "review_assignment":{
    "view":{
      "reviewer_id":{
        "$isNull":false
      },
      "template_id":"jwtPermission_array_bigint_template_ids"
    }
  }
}
```
If you want to try this I saved a snapshot on templates repo `dev/snapshots/newPolicy_SamePatter` with your code, please have a look and let me know if you can see why the rules don't apply correctly.

**Comment by andreievg** [comment]
Oki, it looks like the only problem was template wasn't linked to permission_name through template_permission. 

I used the snapshot you've suggested and didn't change any policies. (using policy rules you've suggested, thanks!, which look good to me, I haven't really tested the ones I've provided so possible they were erroneous).

Debugging:
* Test with permissions (can't access as `nicole` but can access as `jess`
* Tested without permission (just with `yarn pg`), and can access by nicle
* Switched back to permissions (`yang pg_permissions`)
* Had a look at the request in browser and got this jwt: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJwb3N0Z3JhcGhpbGUiLCJ1c2VySWQiOjQsIm9yZ0lkIjoxLCJzZXNzaW9uSWQiOiJLcnQ0Y1hwZDdsZjlCQ1BhIiwiaXNBZG1pbiI6ZmFsc2UsInBwMiI6InQiLCJwcDJfdGVtcGxhdGVfaWRzIjoiOSwxMCw4NiwwIiwicHA1IjoidCIsInBwNV90ZW1wbGF0ZV9pZHMiOiI5LDEwLDExNywxMzAsMTMxLDEzNCwxMzkiLCJwcDciOiJ0IiwicHA3X3RlbXBsYXRlX2lkcyI6IjEzNCIsInBwOSI6InQiLCJwcDlfdGVtcGxhdGVfaWRzIjoiMCIsImlhdCI6MTY2MjcwMTA0MH0.jobYAL0yRPAP4vhgoxaXn4vR0t4N5XYooj0ROX6rCRo`
```json
{
  "aud": "postgraphile",
  "userId": 4,
  "orgId": 1,
  "sessionId": "Krt4cXpd7lf9BCPa",
  "isAdmin": false,
  "pp2": "t",
  "pp2_template_ids": "9,10,86,0",
  "pp5": "t",
  "pp5_template_ids": "9,10,117,130,131,134,139",
  "pp7": "t",
  "pp7_template_ids": "134",
  "pp9": "t",
  "pp9_template_ids": "0",
  "iat": 1662701040
}
```
[jwtio](https://jwt.io/)

pp9 template id was missing (0) so i suspected that it's not available. 

Using this query:

```sql
SELECT "user".username,
       organisation.name,
       permission_name.name,
       permission_policy.type,
	   permission_policy.name,
	   "template".name,
	   "template".version,
	   "template".id
FROM   permission_join
       join "user"
         ON "user".id = permission_join.user_id
       join organisation
         ON organisation.id = permission_join.organisation_id
       join permission_name
         ON permission_name.id = permission_join.permission_name_id
       join permission_policy
         ON permission_policy.id = permission_name.permission_policy_id 
	   join template_permission
	     ON template_permission.permission_name_id = permission_name.id
	   join "template"
	     ON "template".id = template_permission.template_id
```

notice that once I join template_permission the pp9 (permission_policy 9) and associated policy name disappear, so it seems template permission was missing for it. I couldn't change in template builder UI since template wasn't draft so did manualy:

`insert into template_permission (permission_name_id, template_id) values(53, 134)`

and then ran `yarn ts-node ./database/updateRowPoliciesCLI.ts`

and it's worky now
