### ISSUE TITLE
Epic #63 -  Lock review submission

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#526]
## Description

When a partial review is done by others they can be consolidated. And if the consolidation continues to besent back to Applicant, your review is "Locked" which means it can't be submitted (but you can still continue to review).

## Documentation
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials

### Sprint 34:
- [x] Create action to lock reviewer of sections (Review lvl 1) when after LOQ is submitted #440 
- [x] When LOQ or non conformity decision is made lock other reviews [Back-end#364](https://github.com/openmsupply/application-manager-server/issues/364) PR [#375](https://github.com/openmsupply/application-manager-server/pull/375) 

### Sprint 35:
- [x] Should we change the reviewAssignment.isLocked to true when there is a Review and it has been set to LOCKED status? #757

**Comment by nmadruga** [comment]
See this [comment](https://github.com/openmsupply/application-manager-web-app/pull/493#issuecomment-805411817) from Andrei that should help when working on this
