### ISSUE TITLE
Epic #87 - Production build (back and front end)

### ISSUE THREAD

**Issue by andreievg** [openmsupply/conforma-web-app#543]
* Scripts (maybe in seperate repo), to build both back and front end
* Push release to docker cloud 
* Instructions on how to deploy and how to re-deploy (switch servers)
* Back ups ?
* Optimise build for bundle size
* Build server ? (manually)

Production ready:
- Log problems with the Actions
- Mopping on server to remove old UserRegistration not submitted
- Plugin and actions

Although priority of this epic is 3 (for overall outcome), we do want to provide dockerised version for stakeholders. Thus some of the issues have been prioritised to priority 1

### Tasks
- [x]  https://github.com/openmsupply/application-manager-server/issues/306
- [x]  https://github.com/openmsupply/application-manager-server/issues/309
- [x]  Set up push to docker cloud
- [x] #624

### Sprint 48:
- [x] Deployed with docker?
- [x] #119

### Further tasks
- [ ] Authentication for all rest endpoint (ex: uploading files)
- [ ] Safety for filters on postgraphile
