### ISSUE TITLE
Epic #85 - Bug Fixes (and refactor)

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/conforma-web-app#546]
So we factor time taken fixing bugs into our planning

### Sprint 27:
- [x] https://github.com/openmsupply/application-manager-server/issues/274
- [x] #494
- [x] #304 

### Sprint 28:
- [x] #558
- [x] #559
- [x] #450
- [x] #609

### Sprint 29:
- [x] #620 
- [x] https://github.com/openmsupply/application-manager-server/issues/282
- [x] https://github.com/openmsupply/application-manager-server/issues/221
- [x] https://github.com/openmsupply/application-manager-server/issues/312 PR https://github.com/openmsupply/application-manager-server/issues/320

### Sprint 30: 
- [x] #589
- [x] https://github.com/openmsupply/application-manager-server/issues/312

### Sprint 31:
- [x] #653 PR #660
- [x] #655 PR #657
- [x] #625 PR #655
- [x] #658 PR #663
- [x] #665 [PR-Back-end#335](https://github.com/openmsupply/application-manager-server/pull/335)
- [x] #668 PR #669

### Sprint 32:
- [x] #654 

### Sprint 33:
- ~~#685~~ INVALID
- [x] #638 PR #710

### Sprint 35:
- [x] Fixes for parameter evaluation: default in text fields, and pass down "internal" expressions #745

### Sprint 36:
- ~~https://github.com/openmsupply/application-manager-server/issues/221~~ DUPLICATE
- ~~https://github.com/openmsupply/application-manager-server/issues/218~~ INVALID
- [x] #717

### Sprint 37:
- [ ] #760 ~**In Progress**
- [x] #777 PR #791

### Sprint 38:
- [x] #804 PR #807
- [x] #796 PR #809
- [x] https://github.com/openmsupply/application-manager-server/issues/413 PR https://github.com/openmsupply/application-manager-server/issues/421
- [x] https://github.com/openmsupply/application-manager-server/issues/399
- [x] #796 PR #809

### Sprint 39:
- [x] #818 PR #819

### Sprint 40:
- [x] https://github.com/openmsupply/application-manager-server/issues/433 PR https://github.com/openmsupply/application-manager-server/pull/434

### Sprint 42:
- [x] #855 PR #856
- [x] #846 PR #858
- [x] #845 PR  #848

### Sprint 43:
- [x] #859 PR #862
- [x] #861 PR #862
- [x] #874 PR #881
- [x] #866 PR #882
- [x] #857 PR #860 
- [x] https://github.com/openmsupply/application-manager-server/issues/472 PR https://github.com/openmsupply/application-manager-server/pull/473 
- [x] https://github.com/openmsupply/application-manager-server/issues/483 PR https://github.com/openmsupply/application-manager-server/pull/456

### Sprint 44:
- [x] #690 PR https://github.com/openmsupply/application-manager-server/pull/479
- [ ] #828 ~In Progress
- [ ] #878 ~In Progress
- [x] #879 
- [x] #789
- [x] #850
- [x] #868 
- [x] https://github.com/openmsupply/application-manager-server/issues/442
- [x] #775
- [ ] #767
- [ ] #776

### Backlog:
- [x] #821
- [x] #822
- [x] https://github.com/openmsupply/application-manager-server/issues/297
- [ ] #867
- [x] #869
- [ ] #740
- [ ] #637
- [x] #692
- [ ] #637 
- [ ] #575
- [ ] #186
