### ISSUE TITLE
Epic Lookup Tables

### ISSUE THREAD

**Issue by andreievg** [openmsupply/conforma-web-app#55]
Lookup tables are arbitrary, user created tables populated with data. They can be queried by evaluator for things like options in option list.  

For now we think that lookup tables will not have any join. Will be editable only by import

**Scope of this issue**

* End point to access lookup tables
* Can view all of the lookup tables (very simple implementation of https://react.semantic-ui.com/collections/table/, no pagenation required)
* Can select individual lookup table
* Can create new lookup table
* When selection or creating a new table, can view data in that table (https://react.semantic-ui.com/collections/table/, with basic pagenation)
* Can export to csv
* Can import from csv

* When importing to a completely new table
  * Show some basic statistic of import
  * Columns should be created
  * IDs generated
* When importing to an existing table
  * Show some basic statistic of import and of changes
  * New columns created if needed
  * Either add or change entities

* Creating new lookup table should not conflict with any existing tables

**Super draft outline of implementation**

`Back End`

* Lookup tables to be identify-able by a prefix (i.e. lookup_table_{tableName})
* New REST endpoint to list all of the lookup tables (and maybe their structure)
* New REST endpoint to create columns of a lookup table
* New REST endpoint to create lookup table
* New REST endpoint to get an export (or can front end generate it after GraphQL query ?)

`Front End`

* Two new routes, to list them and to view individual lookup table
* GraphQL for inserting/updating records
* Import, export and create table buttons in respective routes
* How do we summarise to the user the things that will be changed/added ?

**Deliverables** `steps of implementation`

* Provide estimate of delivery
* Draft initial internal documentation (including possible break down of issues), this documentation can just be a comment in this epic, outlining detailed approach of implementation
* Ask for review of initial internal documentation
* After review of initial internal documentation, provide refined estimate of delivery
* PRs
* Refined internal documentation (in appropriate documentation folders of each repo)

**Lookup tables Beyond This Epic**

This is just a brainstorm, some of the below may not go into mvp

* Permissions
* Editing via UI
* Delete lookup table

**Comment by sworup** [comment]
Hi @andreievg, I have created of an overview of what I understood about this Epic. I have boken down the steps basically in terms of UI interface for simplisity, just to know if I am correct. I will break them down into issues soon after your feedback.

## Overview

I am presuming the functionalities below based on the little research I have had since yesterday evening 😃. So please feel free to correct me if I am wrong.

- Lookup tables are actually just in view form and not actual table with data in it. When we view a lookup table, the data table on UI is generated based on evaluators and is not stored anywhere in database (except for the tables own information). **So tables are stored but data is queried.**
- Lookup tables are basically query builders visualized as simple tables 
- We can select, edit and delete options and option lists. 
- We can preview the lists in simple table form. 
- We can add and delete table columns to customize the information shown
- When we are done, we save the table and evaluator query will be updated to reflect the changes.
- You can go to Lookup tables page to see the list of available lookup table 
  - ...and edit, delete any of them as we choose to.
- We can import from CSV and the lookup table along with the CSV data submitted will be uploaded to database
- We can export the lookup table with its resulting data in CSV form

## Front end

> **Note:** Some pages can be popups

### List lookup tables (MVP) page
- Page has simple react table that list lookup table names 
	- Has a **view** button to open individual lookup table in read-only mode
	- Has a **edit** button to open individual lookup table in edit mode 
	- Has a **delete** button to delete individual row
	- Has a **export** button to export individual row to csv
- Page has a **Add new lookup table** button to open a page that create new lookup table
- Page has a **import** and **export** to bulk import or export

### View individual lookup table (MVP) page
- Show the lookup table's title at top
- Page has edit button that will take you to edit page
- Page has delete button that will delete the lookup table
- Page shows the evaluator json object 
- Page shows the lookup table in simple table form (cannot be edited) with data that was queried with evaluator query.
- Export button to export individual lookup table interface

### Edit individual lookup table (MVP) page
- Title in input box can be updated
- Show evaluator 
	- Drop-down to select evaluator if it comes from other source
  		-  Show evaluator object in json form
  		-  cannot be edited
	- or Show evaluator editor (if we store evaluator query json along with lookup table)
- Show an editable lookup table. 
	- If there is a valid evaluator and a corresponding field map, pre-populate the table
	- This table updates when user interact with above evaluator UI
  		- Maybe save column mapping json in memory while user is updating and experimenting with table columns as a hard reset on evaluator change might be jarring to users
	- The table headers will be editable, the body will adjust accordingly with data queried with change in evaluator query or table columns map as the user edits them
  - Has buttons to add and edit columns
  - Can update column names
  - Can map columns to evaluator node ends 
  - The add, edit buttons and map interface will update the column map json object which will be saved on save button click
- Save button to save the edit
- Delete button to delete the table entry
- Export button to import and export individual lookup table interface (this will override user made changes)

### Add new lookup table (MVP) page
- Add and edit pages could use the same component with slight changes based on which type of operation it is.
- Will not have delete button

#### Validation
- Lookup table name (slug) should be unique 

### Import lookup table CSV (MVP) interface
- Can be used for both bulk and individual table import
- A progress bar to show file import (upload)
- Validate csv file, show progress to user interface
- Success or fail upload and validation message
- Show what has changed in a detailed interface
- Are you sure you want to finalize the import
	- If yes complete the import
	- Close popup 
	- Updated lookup table interface

### Export lookup table CSV (MVP) interface
- Can be used for both bulk and individual table export
- On click generate the CSV and provide link (no UI needed)

## Back-end

Based on the observation above I presume the back-end would need this database table:

### Table structure

**New table required:** `evaluator_lookup` (or something else)

| Field name                | Type                 | Description                                                                                                |
| ------------------------- | -------------------- | ---------------------------------------------------------------------------------------------------------- |
| id                        | Alpha                | Primary key                                                                                                |
| title                     | Text                 | Title to be shown to user on table listing and in edit page                                                                |
| name                      | Text                 | Name of the lookup table to be used internally or in URL slug (can be generated from title)                | 
| evaluator_id or evaluator | Alpha or json object | Can be id to evaluator query table or if we are keeping the data in this table, can be json evaluator text |
| column_map                | json object          | Column map for evaluator node field to lookup table's column                                               |
| created_on                | datetime             |                                                                                                            |
| last_edited_on            | datetime             |                                                                                                            |

- column_map could be an array of this format (rough guessing)
	```
	[
		{
			"title": "ID",
			"position": 1, 
			"evaluator_node_end": "application.node.ID" 
		},
		{
			"title": "Question",
			"position": 2,
			"evaluator_node_end": "application.node.question_text" 
		}
	]
	```

### GraphQL endpoints

- List all lookup tables
- Create new lookup table
- View individual lookup table
	- Edit individual lookup table
	- Delete individual lookup tree
- Add column(s) to a lookup table
- Delete column(s) from lookup table
- Import from CSV 
	- This will import data too right? So multiple tables will be updated
		- Maybe we need an endpoint to do the upload and validation first 
			- Send expected changes to user
		- then use another endpoint to do the actual import
- Export to CSV

**Comment by andreievg** [comment]
@Sworup, I've started looking at this and came across some comments:

Andrei:
> Lookup tables are arbitrary, user created tables populated with data

Sworup
> Lookup tables are actually just in view form and not actual database tables

They should be database tables. Evaluator already has the ability to query any table with GraphQL. So we need to have an ability to import/export tables with CSV for MVP. By the way Postgraphile, updates schema automatically (GraphQL schema, to match postgres schema)

> Lookup tables are basically query builders visualized as simple tables

Can you please point out, from the original issue, where this spec came from ?

Can you please re-write the spec following the original issue. (which is just and ability to import a lookup table from CSV, export lookup table to CSV, and view lookup table, nothing evaluator related).

**Comment by sworup** [comment]
Summary of Zoom meeting I had with @andreievg on March 5th. 

# MVP requirements for Lookup-tables, issue breakdown

## Server side
- [ ] Create a table in database `lookup_table` to list names of all the lookup tables
- [ ] Create a Fastify endpoint to import CSV, validate the data, create or update database table and return JSON response
- [ ] Create a Fastify endpoint to export lookup table as CSV

## Web app
- [ ] List page for all the lookup tables
- [ ] View page for individual lookup table
- [ ] Import and export CSV buttons and validation pop-up UI

**Comment by sworup** [comment]
# Issues

- [ ] Create lookup-table listing and individual table page (#448)
