### ISSUE TITLE
Epic #89 - Review Re-assignment

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#564]
When review is re-assigned to another reviewer a new review_assignment should be created, but also dealt correctly with the previous review assignment to not be able to continue to review, and any reviewed questions get re-assigned to the new reviewer as well. A message to the Assigner should be displayed before the re-assignment is done.

## Documentation
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials

### Sprint 50:
- [x] https://github.com/openmsupply/application-manager-server/issues/475 PR #982 & back-end https://github.com/openmsupply/application-manager-server/pull/574

### Sprint 51:
- [x] https://github.com/openmsupply/application-manager-server/issues/577 PR #994 & back-end https://github.com/openmsupply/application-manager-server/pull/586
- [x] #987 PR #995 
- [x] https://github.com/openmsupply/application-manager-server/issues/429

### TODO: Create Issues
- [x] Reassignment 
- [ ] Warn user when re-assigning where review was started

**Comment by nmadruga** [comment]
## Summary of the existing Assignment logic

### How review assignments are created?
On action called **generateReviewAssignment**. This actions does quite a lot, currently triggered by:
- ON_APPLICATION_SUBMIT: To generate the review assignments for all users with permission to review on level 1 in the first stage as defined in the template associated with this application.
- ON_REVIEW_SUBMIT: When submitting to the next level/stage review, which can be one of the following options:
  - If stage has more than one level: with ANY decision made (Reject/Approve)
  - If is_last_level in stage: when decision IS Approve (goes to next stage)

### How does assigner gets to assign reviews?
Also done in **generateReviewAssignment**. ReviewAssignment gets a ReviewAssignmentAssignerJoin created to associate a user with permission to assign in this stage/level as defined in the template associated with this application.

**Comment by nmadruga** [comment]
## Proposed solution for Re-assignment and Un-assignment

This is all considering previous conversation with the team and what Carl and I had discussed today about re-assignment and triggers...

### Step 1
- Adding option to Re-assign without copying any reviewResponses (also called Transfer ownership)
- Allow ReviewAssignment to get un-assigned. 
- Allow for Re-assignment of a section. This is already partially implemented in the Front-end PR #982. 

#### Unassignment
If the Review for the assignment has already been submitted (at any time in the past) it should allow to be Un-assigned
**Note**: UI that disable the dropdown should be covering the case of Review is draft (previously submitted).

When Un-assigning a section:
- change ReviewAssignment status to AVAILABLE
- if the ReviewAssignment already has a Review in DRAFT this will have new status = DISCONTINUED. 
- same rules to auto-assign should apply, so if reviewer `is_last_level` or `is_self_assinable` or `make_final_decision` then all sections need to be un-assigned. 

Then in case this reviewAssignment gets (for any reason) re-assigned back to the same reviewer, the previous Review isn't continued, and a new one should be created instead. So new this ReviewAssignment would have 2 Reviews associated, but only one with status not DISCONTINUE should be considered.

When is this new Review created? When the user clicks to start - So will need to add some logic to check for either no review or the existing review is DISCONTINUED and start another review.

🔝 should be done in issue #987 

#### Reassignment
- After the Assigner clicks on the option **re-assign** on the dropdown, a second dropdown appears
- Allows selecting one of the other ReviewAssignment with status as **Available**. 
   - Note: now Available and Available_for_self_assignment are the same.
- If this is a Self-assignment it would require that first the sections are un-assigned to then allow the reviewer to load the Review page and now have the option `self-assign`.
- After selecting the new Reviewer the re-assignment happens. A mutation to change both ReviewAssignment statuses (since it's the assigner that has access to both ReviewAssignment and ReviewQuestionAssignment):
```
mutation reasignReviewAssignment(
    $unassignmentId: Int!
    # $unassignmentStatus: ReviewAssignmentStatus = AVAILABLE
    $reassignmentId: Int!
    $reassignmentPatch: ReviewAssignmentPatch!
  ) {
    reassignmentUpdate: updateReviewAssignment(
      input: { id: $reassignmentId, patch: $reassignmentPatch }
    ) {
      reviewAssignment {
        ...ReviewAssignment
      }
    }
    unassignmentUpdate: updateReviewAssignment(
      input: { id: $unassignmentId, patch: { status: AVAILABLE, isLocked: true } }
    ) {
      reviewAssignment {
        ...ReviewAssignment
      }
    }
  }
```
Now we need an action in the back-end to deal with Reviews...
- Probably just one trigger is enough for now ON_REVIEW_REASSIGN which gets set on the review being unassigned (so we now which one was it) and change the Review status to DISCONTINUED

### Step 2
- Allow assigner to select if wants to transfer review from previous Reviewer. That could be implemented later on, but for now it would just add more complexity and maybe isn't required.
- We shouldn't re-link any ReviewResponses, Review, etc. Instead Generate copies of the Review, responses and decision to the create a new Review for the Re-assigned reviewer. Now they own this review, but kept the hisotory of ownership.

**Comment by CarlosNZ** [comment]
>     * ASSIGN_LOCKED => All sections review assignments == **Assigned** and All Review status == **Submitted**

I don't understand this one. What is it for? If all reviews are Submitted, why do you need to lock anything?


This looks pretty good, it sounds like it covers everything.

So to clarify -- when re-assigning, the new reviewer will have to start again, and the previous reviewers review_responses will become "dead", essentially? 

My only concern is if an assigner re-assigns someone and makes a mistake, they should be able to re-assign it back to the original reviewer without any loss -- i.e. the original reviewer shouldn't have to start again just because their boss accidentally messed with their assignment. Will this work? Will the original review responese keep their link so that assigning back to the original reviewer keeps everything intact?

> **Note**: On PR #982 have changed to only use Available and Assigned, and add field `isSelfAssignable` due to on re-assignment is impossible to now if a ReviewAssignment set as Assigned used to be Available or Available_for_self_assignment

I think this is a good idea. I've never really liked the "available for self-assignment" and "available" being different. Makes sense to keep the "self assignable" part separate to whether or not its available. 👍

**Comment by nmadruga** [comment]
> > ```
> > * ASSIGN_LOCKED => All sections review assignments == **Assigned** and All Review status == **Submitted**
> > ```
> 
> 
> I don't understand this one. What is it for? If all reviews are Submitted, why do you need to lock anything?

To prevent action **re-assign** from showing up for that application on the list - For assigners

**Comment by CarlosNZ** [comment]
> To prevent action **re-assign** from showing up for that application on the list - For assigners

Okay, I thought "Actions" were things they could do -- so why would Assigner need to "LOCK"? But it's just so the front-end knows what to display for user, right?

**Comment by nmadruga** [comment]
> So to clarify -- when re-assigning, the new reviewer will have to start again, and the previous reviewers review_responses will become "dead", essentially?

Yes. That's the idea. Some logic will need to be added to Front-end as well to make sure we create a new Review when there is already one linked to the ReviewAssignment with status DISCONTINUED

> My only concern is if an assigner re-assigns someone and makes a mistake, they should be able to re-assign it back to the original reviewer without any loss -- i.e. the original reviewer shouldn't have to start again just because their boss accidentally messed with their assignment. Will this work? Will the original review responese keep their link so that assigning back to the original reviewer keeps everything intact?

Well - at the start this Review is set to status DISCONTINUED, but we can add a check in UI so the user can decide to simply continue. Or we would always keep the existing Review by changing it's status back to ASSIGNED, but that would be required to add a new action to be triggered ON_REVIEW_ASSIGN to check for existing Review and update the status.

**Comment by nmadruga** [comment]
> why would Assigner need to "LOCK"? But it's just so the front-end knows what to display for user, right?

Yes, that was my thinking - by the way, this is already implemented and merged to `main` (in PR #926), maybe this actions wasn't requried and the Re-assign could only just not be returned in case all reviews have been submitted. Probably something good to check during the implementation of re-assignment + if we check for reviews that have been submitted and not only that have the review status as SUBMITTED, since they may be in PENDING or other status which can't be re-assigned (for Phase 1 at least).
