### ISSUE TITLE
Epic #8 - Basic Application Skeleton (Use Registration)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#70]
## Description
In the App's public page there are options to Login or Register Applicant. When user wants to Register the form is displayed as a Template Applications (without Reviews).
The Application page shows the template sections and pages with template question fields (using the question plugin). 
Each template question field is respecting the general rules defined in the question plugin and the specific rules defined in the template question. 

## Issues
Total effort: 34

### Sprint 1-3:
Summed effort: 14
- [x] #11 Add Drug Registration template to the schema (AVG Effort: 2)
- [x] #18 New action to create users (AVG Effort: 2)
- [x] #19 Build User Registration UI (AVG Effort: 2)
- [x] [Back-end#56](https://github.com/openmsupply/application-manager-server/issues/56) Fastify endpoint for checking uniqueness username/company (AVG Effort: 2)
- [x] #53 List of actions for User Registration (AVG Effort: 2)
- [x] #14 Build elements for basic User registration application - Effort 4

### Sprint 4:
Summed effort: 6
- [x] #28 Create custom hook to call getTemplate query - Effort 1
- [x] #29 Create custom hook to call getApplicatio query - Effort 1
- [x] #30 Create custom hook to call createApplication mutation - Effort 1
- [x] #31 Create custom hook to call getElements query - Effort 1
- [x] #52 Fix Question/Elements are not showing on each page - Effort 2

### Sprint 5:
Summed effort: 8
- [x] #36 Replace use of refetchQuery with readQuery and writeQuery for better latency feedback. (AVG Effort: 2)
- [x] [Back-end#77](https://github.com/openmsupply/application-manager-server/issues/77) Figure out the best way to handle sequential actions. (AVG Effort: 2)
- [x] [back-end#82](https://github.com/openmsupply/application-manager-server/issues/82) Modify schema to use index for ordering sections and elements. (AVG Effort: 2)
- [x] #58 Update elements order by index. (AVG Effort: 2)

### Sprint 6:
Summed effort: 6
- [x] #51 Problem controlling state when page is refresh or link followed - Effort 1
- [x] #47 Basic application submission logic + summary page - Effort 4

### Documentation:
- [ ] docs external
- [ ] docs internal - #3 Documentation front-end, examples and states definition

- Wireframes for Desktop: https://debs181572.invisionapp.com/console/share/6N1N4YOR4Y
- Wireframes for Mobile: https://debs181572.invisionapp.com/console/share/3K1MPN0GGM
