### ISSUE TITLE
Epic # 9 - In Progress application

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#73]
## Description
First example applications: Create company and Join company
On the initial designed pages, we can simply add the Templates to the database.
Create the In-progress Application page to display either: new Draft Application, **existing Draft**.
The current page is either: the first (visible) or the first page with invalid fields - to be completed or continued. 
Show the progress bar and options to continue to next page, go to other sections. Applicant can see the validation, the responses entered and their full progress. Refreshing the page will  keep the Applicant's responses.

### Sprint 7:
- [x] #38 Research how to define queries to be fetching or use cache - Effort 1
- [x] #37 Research how to send cached local changes to the server in one call. Example: update cache onChange of responses and then send a mutation to the server when click the Next button - Effort 1
- [x] #39 Progress bar in application page - Effort 2
- [x] #35 Hook to query the full application, sections and elements and create flatten object with all questions and responses (AVG Effort 2)
- [x] #46 Persist cache - Effort 2
- [x] #44 Make sure context state of questions and responses is changed when response is written to cache - Effort 1

### Sprint 8:
- [x] #67 Go to some page in application when click on an application with Draft status - Effort 2

### Sprint 9:
- [x] #71 Validation before update of the response in cache/server - Effort 1

### Sprint 10:
- [x] #81 Progress bar 'state' logic - Effort 4
- [x] #92 Fix warning about ApplicationViewWrapper of ShortText when the response is null - Effort 1

### Sprint 11:
- [x] #130 useGetResponsesAndElementState hook -- should only return 2 objects, not 3 - Effort 1
- [x] #162 Automatically add asterisk in required elements fields on the UI - Effort 1
- [x] #142 Linear application: Show message about validation when click 'Next' or other page in the progress bar - Effort 1
- [x] #136 Show validation in page for linear application after clicking the Next button - Effort 1
- [x] #124 Evaluate template element parameters in UI  - Effort 2

### Sprint 12:
- [x] #192 Remove "Review and Submit" from progress bar and display as button - Effort 1
- [x] #180 Implement `isEditable` restriction in Element (plugins) - Effort 1
- [x] #196 Bug -- Validation of Linear forms - problems with multi-pages/multi-sections - Effort 1
- [x] #194 Validity check updates (Summary/Submit) - Effort 3

### Sprint 13:
- [x] #135 Redirect Draft application to page in progress  - Effort 1
- [x] #206 Bug: Fix problem with allowing user to go to another page (after the first one is valid) on linear Application - Effort 1
- [x] #214 Bug: Clicking Next while still focused in Text input field doesn't validate - Effort 1
- [x] #170 Bug fix -- starting a new application of same type of previously unfinished application loads the summary page - Effort 1 

## Design
* Summary: <img width="533" alt="Screen Shot 2020-11-09 at 3 28 57 PM" src="https://user-images.githubusercontent.com/16461988/98493833-5ae4fc00-22a0-11eb-80cb-fc02dded0a3a.png">
- Wireframes for Desktop: https://debs181572.invisionapp.com/console/share/6N1N4YOR4Y
- Wireframes for Mobile: https://debs181572.invisionapp.com/console/share/3K1MPN0GGM
