### ISSUE TITLE
Epic #10 - App Layout and Styles

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#78]
## Description
Top bar: App logo and name; 
User menu: Name, company, notifications, Log-out; 
Left nav bar: available options/categories and each options that the Applicant can view apply. All options will be linked to what permissions the Applicant has on the JWT Token - the minimal set is: Create a company and Join a Company.

### Documentation:
- ~~#184 Display application types in navigation based on current user permissions~~ Duplicated
- [x] #139 Component consistency/Style discussion

### Sprint 8:
- ~~#64 Front-end query server to get template types and actionable (based on template type) that the current user is allowed and display on App navigation~~ (Relocated to epic 11)

### Sprint 16:
- [x] #161 Dynamically display template options based on user permissions - Effort 3

### Sprint 28:
- [x] Remove many Semantic themes (that aren't in use) to speed up the first compilation for the front-end bundle #191 **PR #612**
- [x] Global font and colours #586 **PR #612**
- [x] App container & User Area -- layout & styles #148
#### Break-down to replace element tags styles for each existing page in the app
- [x] Update layout and use global styles: Application create page #593 PR #619
- [x] Update layout and use global styles: Application home page #597 PR #622
- [x] Add specific title to progress bars on SectionProgress line on ApplicationHome #621
- [x] Update layout and use global styles: List page #592

### Sprint 30:
- ~~Improve front-end hot reloading to only transpile CSS files with new changes #613~~ INVALID
- [x] Update layout and use global styles: Login page #591
- [x] Update layout and use global styles: Application page + Progress Bar #594 Part 1 - PR #647
- [x] Update layout and use global styles: Review home page #599 PR #650

### Sprint 31:
- [x] Update layout and use global styles: Application Summary page #595 PR #671
- [x] Update layout and use global styles: Review page + Submission modal #598 PR #673
- [x] Update layout and use global styles: Application Submission page #596 PR #679
- [x] Update layout and use global styles: Application + Summary + Template question plugins #600
- [x] Element plugins -- add "help" field #645 ~**In PR**

### Sprint 32:
- ~~Progress bar: UI when page has no required elements -- to consider #298~~ WONTFIX
- ~~Improvements to sticky section titles on ReviewPage and ApplicationSummary #588~~ INVALID
- [x] Quick fix: List layout issue (Edit draft) #661

### Sprint 33:
- [x] Change links in the list to go to the Review home page for reviewers and hide the expansion icon #703
- [x] Show Application title on the Review home page with link to application summary page #704

### Sprint 34:
- [x] Update layout and use global styles: All remaining elements #662 ~**In Progress**
- [x] Show Application title on the Review home page with link to application summary page #704

**Comment by nmadruga** [comment]
Tyding up for `SectionSummary` and `ReviewSummary` page (Applicant and Review): 
- Should the collapsed/Expanded sections should be persisted in the current section? 
- Should we show the summary page for the Applicant with all section expanded at the start? What about for the reviewer, only the sections they are assigned to do and haven't finished?

**Comment by nmadruga** [comment]
Create component to wrap common pages that uses the company title in the header (with styles) OR just repeat this header and use class to style different pages at the same time. As per https://github.com/openmsupply/application-manager-web-app/pull/266#discussion_r560507543

**Comment by nmadruga** [comment]
Needs to tidy how the Review decision display on the Review & Consolidator page, for now is very basic:
<img width="882" alt="Screen Shot 2021-01-21 at 11 49 37 AM" src="https://user-images.githubusercontent.com/16461988/105250509-c1f72900-5bde-11eb-96e7-1ae461946152.png">

But it should look like:
<img width="498" alt="Screen Shot 2021-01-21 at 10 14 20 AM" src="https://user-images.githubusercontent.com/16461988/105239167-a0437500-5bd1-11eb-8b74-83e995764e04.png">
