### ISSUE TITLE
Epic #13 - Application Changes Requested

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#94]
## Description:
After the Application goes through a initial review and comes back to the Applicant OR comes back to the Reviewer (from the consolidator) to have another go - Edit application - the UI needs to display some new features and new records need to be created by mutations to allow the user to enter **new** responses in the application/review of application.

### Applicant
The user should be able to see the start page and click a button to **Make changes**.
The questions on application can now be edited (all questions are editable) with highlight for what was meant to be changed in the review. On the `Application page` the Applicant can see all fields and previous responses. The `Application start page` should take the user to the page where there is a **change required** which is where it can be edited.
After the user re-submits the Application it is only visible but not editable anymore. The new status is **Re-submitted**.
If the page is refreshed new responses should be kept. Closing the page also keeps the responses saved for the applicant.

### Reviewer
The user should be able to see the start page and click a button to **Continue** with changes requested.
All the review responses can now be edited with highlight on the ones required by the Consolidator (disagreement). On the `Review page` the Reviewer can see all fields, previous review responses and disagreements. The `Review start page` should take the user to the page where there is a **change requested** which is where it can be edited.
After the user re-submits the Review it is only visible but not editable anymore. The new status is **Submitted**.
If the page is refreshed new reviews should be kept. Closing the page also keeps the reviews saved for the reviewer.

### After changes are made
**TODO**> Write about Reviewer and Consolidator perspective after the changes are made by the solicited user...

## Documentation
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials

### Sprint 20:
- [x] [Back-end#137](https://github.com/openmsupply/application-manager-server/issues/137) Create Action to trim unchanged responses on submission - Effort 3

### Sprint 21:
- [x]  [Back-end#211](https://github.com/openmsupply/application-manager-server/issues/211) Design how to set review_responses to be visible to Applicant when LOQ is created - requires new field - Effort 2

### Sprint 23:
- [x] [Back-end#228](https://github.com/openmsupply/application-manager-server/issues/228) Update actions that trim applicationResponse and reviewResponses not changed during submission to update the time submitted of responses that have been changed - Effort AVG: 2 ~**In PR**

### Sprint 24:
- [x]  [Back-end#231](https://github.com/openmsupply/application-manager-server/issues/231) original response to be associated to every review_response on creation (if possible) - Effort: 1
- [x]  [Back-end#232](https://github.com/openmsupply/application-manager-server/issues/232) is visible to applicant logic on back end (LOQ proposal diagram) - Effort: 2
- [x] [Back-end#233](https://github.com/openmsupply/application-manager-server/issues/233) action to change application status on review submission of last level with decision LOQ - Effort: 2
- [x] [Front-end#421](https://github.com/openmsupply/application-manager-web-app/issues/421) is visible to applicant logic on front end (LOQ proposal diagram) - Effort: 2 ~**In PR**
- [x] [Back-end#235](https://github.com/openmsupply/application-manager-server/issues/235) action to change review to appropriate status when application is re-submitted (only updates status for application responses that were changed that are assigned to reviewer) - Effort: 3 ~**In PR**

### Sprint 25:
- [x] #314 Duplicate application_responses when user clicks Make changes on Application Start page - Effort: AVG 2
- [x] #437 UI to show to applicant that changes are requested (Application home page) - Effort: 2
- [x] #443 UI to show to reviewer that changes were made (Review home page) - Effort: AVG 2

### Sprint 26:
- [x] #423 review responses 'duplication' (i.e. re-start review) - Effort: 4
- [x] #473 Update URL query when Sections opened/closed - Effort: 1
~~[Back-end#251](https://github.com/openmsupply/application-manager-server/issues/251) Configure action for screening to change outcome to 'rejected'~~
~~[Back-end#171](https://github.com/openmsupply/application-manager-server/issues/171) Create second review after a Review has "Changes Required" or "Pending Review"~~
~~#313 Restrict the query to only return one response per element (when there is more than one return the most recent)~~
~~Action to change status of Review/Application based on decision made by consolidator~~
~~Action to change status of Review based on application re-submission made by applicant~~
~~Add action to create new review_assignment for reviewers lvl 1 when changing to next stage~~

### Sprint 27:
- [x] #441 UI to show which questions need updating (Application Page & Application Summary) - Effort: 3 ~**In PR**
- [x] #442 UI to show reviewer which questions were updated (Review page) ~**In PR**
