### ISSUE TITLE
Epic #17 - Create organisation

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#96]
## Description

Create template for users to be able to create a new organisation in on the system using the Application management workflow. After the template goes through the process of being approved by FDA authorities it gets created in the database and the user who applied is granted owner permission in the organisation to be able to allow other user to join or not the organisation. After the application is approved the use should now have the option to login associated with this organisation and apply for application (Drug registration) as the company as long receive new application to join this organisation.

## Documentation
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials

### Sprint 10:
- [x] [Back-end#97](https://github.com/openmsupply/application-manager-server/issues/97) Create template action to change status of 'Create company' when submit application - Effort 1

### Sprint 18:
- [x] [Back-end#114](https://github.com/openmsupply/application-manager-server/issues/114) Create Company Action 
- [x] #297 updateApplication query should include user and org id - Effort 1
- [x] [Back-end#113](https://github.com/openmsupply/application-manager-server/issues/113) Create action to join username to company when application to 'Create company' is approved - Effort 2
- [x] [Back-end#104](https://github.com/openmsupply/application-manager-server/issues/104) Extend action to grant permission for user link to a company - Effort 2

### Remaining issues to get this all up to MVP:
- [x] "ApplicationData" for front-end evaluator -- put into FullStructure: Issue #458, PR #557
- [x] LongText element plugin: Issue #479 PR #555
- [x] DisplayImage element plugin: Issue #549 PR #556
- [x] "Other" option for RadioButton: Issue #488 PR #554

### Sprint 28:
- [x] Final tidy-ups for Create and Join company #583 **PR #602**
- [x] Rename permission and template names to use org instead of company #308

### Backlog:
- [ ] Template element -- Address autocomplete #552
