### ISSUE TITLE
Epic #16 - List and Filter applications

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/conforma-web-app#98]
## Description

Any logged user can see some applications.
There are options on the left nav bar to select the Application Type to see. After the user clicks on the Application type a list (or cards) is displayed.
There is an option for the user to change from list to cards. After the user picks one option this is persisted on the user's settings.
The list of applications  is associated to:
Current user's permissions (JWT)
Toggled view mode (Apply/Review)
Current Application Type selected
Current filters

### Documentation:
- [x] #225 Documenting List applications headers and functionality - Effort 2
- [ ] TODO: Add as part of [Epic #38](338) Public docs & tutorials 

### Sprint 8:
- [x] #66 Show status/stage of application on the applications list: basically draft and submitted - Effort 1
- [x] [Back-end#99](https://github.com/openmsupply/application-manager-server/issues/99) Show status and stage as "Pending" when trigger is "Processing" - (AVG Effort 2)
- [x] #104 Display loader for application with  application trigger is processing - Effort 3

### Sprint 16:
- [x] #131 Header columns for Application list - Effort 2
- [x] #207 List applications with specific cells on each column  - Effort 3

### Sprint 17:
- [x] #251 Filter application using URL parsed filters - Effort 4
- [x] [Back-end#185](https://github.com/openmsupply/application-manager-server/issues/185) Application VIEW with all relevant columns for list - Effort 3
- [x] #226 Update URL for lists to handle redirects and documentation - Effort 1

### Sprint 20:
- [x] #283 Bug: Too many render calls to ListWrapper when changing the template types - Effort 2
- [x] #210 Use pagination to list applications - Effort 3
- [x] #208 Search applications - Effort 2
- [X] #209 Sort columns - Effort 2

### Sprint 21:
- [x] #329 Application List -- reload only table contents when changing filters #329 - Effort 2

### Sprint 22:
- [x] #211 Expand application sections in list - Effort 2

### Backlog:
- [ ] #363 Show sections of Application in expanded area on the list - Effort 1 - **Might not get implemented**
- ~~#212 Progress logic on Application/Section in the list~~ Duplicated
